### ISSUE TITLE
TA comment: 使用案例圖

### ISSUE THREAD

**Issue by TDyu** [Vanessa1128/BaseProject-Cpp#1]
1. 請繳交至 doc 的文件夾
2. 應有系統邊界（-10）
3. 應至少有5個case在圖中（-10）
4. 若有彼此有關係的case請寫出為include還是extend（-10）
5. 應有其他actor，至少會有房客（-10）

*若有修改，請在此issue下回覆，否則不予修改及加分。

**Comment by Forrest-Li** [comment]
已修改並重新上傳：
作業二 (分組作業)：描繪使用案例圖

**Comment by TDyu** [comment]
> 已修改並重新上傳：
> 作業二 (分組作業)：描繪使用案例圖

已修改分數
